site_name: Wiki
site_url: http://127.0.0.1:8000/
repo_url: https://github.com/jruing/wiki
repo_name: jruing/wiki

use_directory_urls: false
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  highlightjs: true
  plugins:
  - social
  hljs_languages:
    - yaml
    - rust
    - toml
    - css
    - javascript
    - typescript
    - python
    - go
    - html
  features:
    - navigation.instant            # 即时加载
    - navigation.instant.prefetch   # 即时预取
    - navigation.instant.progress   # 进度指示器
    - navigation.instant.preview    # 全局启用即时预览
    - navigation.tracking           # 锚跟踪（类似点击后）
    - navigation.tabs               # 启用选项卡（最顶层）
    - navigation.tabs.sticky        # 粘性导航选项卡（保持可见）
    - navigation.tabs.sections      # 分段
    - navigation.expand             # 展开所有
    - navigation.path               # 导航路径（面包屑）（没效果）
    - navigation.indexes            # 节索引页
    - toc.follow                    # 锚跟随
    - navigation.top                # 返回顶部按钮
    - navigation.footer             # 启用页脚（上一页、下一页）

    - search.suggest                # 搜索建议
    - search.highlight              # 搜索高亮显示
    - search.share                  # 搜索分享
    - content.code.copy             # 代码复制

    - content.action.edit
    - navigation.prune



nav:
  - 简介:
    - 关于: index.md
  - AI:
    - AI_Agent:
      - AnythingLLM+Ollama搭建本地知识库: AI/AIAgent/AnythingLLM+Ollama搭建本地知识库.md
      - LlamaIndex-Agent关联数据库: AI/AIAgent/LlamaIndex-Agent关联数据库.md
      - Llamaindex-Agent自然语言查询数据库: AI/AIAgent/Llamaindex-Agent自然语言查询数据库.md
    - MCP:
      - MCP学习笔记-从0到1: AI/MCP/MCP学习笔记-从0到1.md
      - MCP学习笔记-天气预报: AI/MCP/MCP学习笔记-天气预报.md
      - MCP学习笔记-查询主机资源使用情况: AI/MCP/MCP学习笔记-查询主机资源使用情况.md
    - 其他:
      - Docker安装OneAPI: AI/other/Docker安装OneAPI.md
    - 提示词:
      - deepseekR1增强: AI/prompt/deepseekR1增强.md
      - Graphviz工具: AI/prompt/Graphviz工具.md
      - 互动式零基础教学: AI/prompt/互动式零基础教学.md
      - 人类作者模拟器: AI/prompt/人类作者模拟器.md
      - 单词记忆助手: AI/prompt/单词记忆助手.md
      - 反向PUA: AI/prompt/反向PUA.md
      - 叛逆小子: AI/prompt/叛逆小子.md
      - 可视化网页: AI/prompt/可视化网页.md
      - 天气卡片: AI/prompt/天气卡片.md
      - 归纳总结: AI/prompt/归纳总结.md
      - 源文档到SVG幻灯片生成器: AI/prompt/源文档到SVG幻灯片生成器.md
      - 猫娘: AI/prompt/猫娘.md
      - 黑白系图片生成: AI/prompt/黑白系图片生成.md
      - RooCode角色: AI/prompt/RooCode角色提示词.md
      - 八荣八耻: AI/prompt/八荣八耻.md
  - 自动化:
    - Selenium接管浏览器: automation/Selenium接管浏览器.md
  - 数据库:
    - mysql:
      - Mysql57绿色版安装: database/mysql/Mysql57绿色版安装.md
    - postgres:
      - Postgres学习笔记-Sequence自增序列: database/postgres/Postgres学习笔记-Sequence自增序列.md
      - postgres安装: database/postgres/postgres安装.md
    - redis:
      - Redis7.XCentos集群搭建: database/redis/Redis7.XCentos集群搭建.md
  - 前端:
    - fetch 学习笔记: front/fetch 学习笔记.md
    - Javascript学习笔记-js实现拷贝复制功能: front/Javascript学习笔记-js实现拷贝复制功能.md
    - js控制台Hook: front/js控制台Hook.md
    - React:
      - React-JSX: front/React/React-JSX.md
      - React-Props传递给组件: front/React/React-Props传递给组件.md
      - React-列表渲染: front/React/React-列表渲染.md
      - React-响应事件: front/React/React-响应事件.md
      - React-安装: front/React/React-安装.md
      - React-数据展示: front/React/React-数据展示.md
      - React-更新页面数据: front/React/React-更新页面数据.md
      - React-条件判断: front/React/React-条件判断.md
    - Vue:
      - Vue3 Router路由: front/Vue/Vue3 Router路由.md
      - Vue3+Vite项目基础环境搭建: front/Vue/Vue3+Vite项目基础环境搭建.md
  - Golang:
    - 高阶:
      - Golang 学习笔记-sqlc 代码生成: Golang/advanced/Golang 学习笔记-sqlc 代码生成.md
      - Golang 学习笔记-Viper: Golang/advanced/Golang 学习笔记-Viper.md
      - Golang 学习笔记-结构体与匿名结构体: Golang/advanced/Golang 学习笔记-结构体与匿名结构体.md
      - Golang学习笔记-Casbin学习笔记: Golang/advanced/Golang学习笔记-Casbin学习笔记.md
      - Golang学习笔记-CorbaCLI学习笔记: Golang/advanced/Golang学习笔记-CorbaCLI学习笔记.md
      - Golang学习笔记-jwt: Golang/advanced/Golang学习笔记-jwt.md
      - Golang学习笔记-处理HTTP请求参数: Golang/advanced/Golang学习笔记-处理HTTP请求参数.md
      - Golang学习笔记-定时任务: Golang/advanced/Golang学习笔记-定时任务.md
      - Golang学习笔记-自定义日志轮转及输出: Golang/advanced/Golang学习笔记-自定义日志轮转及输出.md
      - Golang学习笔记-跨平台编译: Golang/advanced/Golang学习笔记-跨平台编译.md
      - Golang学习笔记-令牌桶限流: Golang/advanced/Golang学习笔记-令牌桶限流.md
    - 基础:
      - Golang学习笔记-常量: Golang/tutorial/Golang学习笔记-常量.md
      - Golang学习笔记-变量: Golang/tutorial/Golang学习笔记-变量.md
      - Golang学习笔记-判断: Golang/tutorial/Golang学习笔记-判断.md
      - Golang学习笔记-循环: Golang/tutorial/Golang学习笔记-循环.md
      - Golang学习笔记-数据类型: Golang/tutorial/Golang学习笔记-数据类型.md
  - 云原生:
    - docker:
      - Docker学习笔记-在线安装教程: kubernetes/docker/Docker学习笔记-在线安装教程.md
      - Docker Swarm 学习笔记: kubernetes/docker/Docker Swarm 学习笔记.md
      - Docker-Compose安装: kubernetes/docker/Docker-Compose安装.md
      - Docker学习笔记-redis部署: kubernetes/docker/Docker学习笔记-redis部署.md
      - Docker学习笔记-多阶段构建学习笔记: kubernetes/docker/Docker学习笔记-多阶段构建学习笔记.md
      - Docker学习笔记-安装Nginx及实践应用: kubernetes/docker/Docker学习笔记-安装Nginx及实践应用.md
      - Docker学习笔记-容器镜像导入导出: kubernetes/docker/Docker学习笔记-容器镜像导入导出.md
      - Docker学习笔记-构建私有镜像仓库: kubernetes/docker/Docker学习笔记-构建私有镜像仓库.md
      - Docker学习笔记-镜像体积缩小: kubernetes/docker/Docker学习笔记-镜像体积缩小.md
    - k8s:
      - kubernetes学习笔记-安装: kubernetes/k8s/kubernetes学习笔记-安装.md
      - kubernetes学习笔记-Pod: kubernetes/k8s/kubernetes学习笔记-Pod.md
      - kubernetes学习笔记-NameSpace: kubernetes/k8s/kubernetes学习笔记-namespace.md
      - kubernetes学习笔记-Deployment: kubernetes/k8s/kubernetes学习笔记-Deployment.md
      - kubernetes学习笔记-ReplicaSet: kubernetes/k8s/kubernetes学习笔记-ReplicaSet.md
      - kubernetes学习笔记-Service: kubernetes/k8s/kubernetes学习笔记-Service.md
      - kubernetes学习笔记-ConfigMap: kubernetes/k8s/kubernetes学习笔记-ConfigMap.md
      - kubernetes学习笔记-Ingress: kubernetes/k8s/kubernetes学习笔记-Ingress.md
      - kubernetes学习笔记-helm: kubernetes/k8s/kubernetes学习笔记-helm.md
      - kubernetes学习笔记-搭建K3s集群: kubernetes/k8s/kubernetes学习笔记-搭建K3s集群.md

  - Linux:
    - caddy:
      - caddy简介: Linux/caddy/caddy简介.md
      - caddy手册: Linux/caddy/caddy手册.md
      - caddy安装: Linux/caddy/caddy安装.md
      - caddy静态文件: Linux/caddy/caddy静态文件.md
      - caddy实战-basicauth授权: Linux/caddy/caddy实战-basicauth授权.md
      - caddy实战-反向代理: Linux/caddy/caddy实战-反向代理.md
      - caddy实战-静态站点: Linux/caddy/caddy实战-静态站点.md
      - caddy实战-黑白名单: Linux/caddy/caddy实战-黑白名单.md

    - monitor:
      - Uptime-kuma 监控: Linux/monitor/Uptime-kuma 监控.md
      - 基于Grafana+Loki+Promatil搭建日志分析平台: Linux/monitor/基于Grafana+Loki+Promatil搭建日志分析平台.md
    - nginx:
      - Nginx学习笔记-auth_basic认证: Linux/nginx/Nginx学习笔记-auth_basic认证.md
      - Nginx学习笔记-Centos 7 安装Nginx: Linux/nginx/Nginx学习笔记-Centos 7 安装Nginx.md
      - Nginx学习笔记-Nginx简介: Linux/nginx/Nginx学习笔记-Nginx简介.md
      - Nginx学习笔记-图片防盗链: Linux/nginx/Nginx学习笔记-图片防盗链.md
      - Nginx学习笔记-解决前端后端跨域: Linux/nginx/Nginx学习笔记-解决前端后端跨域.md
      - Nginx学习笔记-负载均衡配置: Linux/nginx/Nginx学习笔记-负载均衡配置.md
      - Nginx学习笔记-部署静态页面实践: Linux/nginx/Nginx学习笔记-部署静态页面实践.md
      - Nginx学习笔记-配置文件详解: Linux/nginx/Nginx学习笔记-配置文件详解.md
      - Nginx学习笔记-黑名单-白名单: Linux/nginx/Nginx学习笔记-黑名单-白名单.md
    - other:
      - linux学习笔记-awk: Linux/other/linux学习笔记-awk.md
      - linux学习笔记-ufw: Linux/other/linux学习笔记-ufw.md
      - linux学习笔记-sudo: Linux/other/linux学习笔记-sudo.md
      - linux学习笔记-cgroup(一): Linux/other/linux学习笔记-cgroup(一).md
      - linux学习笔记-cgroup(二): Linux/other/linux学习笔记-cgroup(二).md
      - linux学习笔记-grep: Linux/other/linux学习笔记-grep.md
      - linux学习笔记-iptables: Linux/other/linux学习笔记-iptables.md
      - Linux学习笔记-jq: Linux/other/linux学习笔记-jq.md
      - linux学习笔记-rsync数据同步: Linux/other/linux学习笔记-rsync数据同步.md
      - linux学习笔记-screen: Linux/other/linux学习笔记-screen.md
      - linux学习笔记-sed手册: Linux/other/linux学习笔记-sed手册.md
      - linux学习笔记-SSH隧道代理: Linux/other/linux学习笔记-SSH隧道代理.md
      - linux学习笔记-Systemd: Linux/other/linux学习笔记-Systemd.md
      - linux学习笔记-tmux: Linux/other/linux学习笔记-tmux.md
      - linux学习笔记-免密登录: Linux/other/linux学习笔记-免密登录.md
      - linux学习笔记-搭建FTP服务: Linux/other/linux学习笔记-搭建FTP服务.md
      - linux学习笔记-服务器基础信息查询脚本: Linux/other/linux学习笔记-服务器基础信息查询脚本.md
      - Ubuntu 22.04 上安装 Python 3.12: Linux/other/Ubuntu 22.04 上安装 Python 3.12.md
    - Prometheus:
      - Prometheus笔记-安装: Linux/Prometheus/Prometheus笔记-安装.md
      - Prometheus笔记-配置文件字段解析: Linux/Prometheus/Prometheus笔记-配置文件字段解析.md
      - Prometheus笔记-安装blackbox_exporter: Linux/Prometheus/Prometheus笔记-安装blackbox_exporter.md
      - Prometheus笔记-安装Node_exporter: Linux/Prometheus/Prometheus笔记-安装Node_exporter.md
      - Prometheus笔记-监控docker容器: Linux/Prometheus/Prometheus笔记-监控docker容器.md
      - Prometheus笔记-file_sd_config: Linux/Prometheus/Prometheus笔记-file_sd_config.md
      - Prometheus笔记-Label标签: Linux/Prometheus/Prometheus笔记-Label标签.md
      - Prometheus笔记-Grafana可视化: Linux/Prometheus/Prometheus笔记-Grafana可视化.md
      - Prometheus笔记-告警规则配置: Linux/Prometheus/Prometheus笔记-告警规则配置.md
      - Prometheus笔记-设置Basic_auth登录校验: Linux/Prometheus/Prometheus笔记-设置Basic_auth登录校验.md
    - serverless:
      - ServerLess学习笔记-搭建FN示例: Linux/serverless/ServerLess学习笔记-搭建FN示例.md
      - ServerLess学习笔记-Fnproject搭建: Linux/serverless/ServerLess学习笔记-Fnproject搭建.md
      - ServerLess学习笔记-Fnproject常用命令: Linux/serverless/ServerLess学习笔记-Fnproject常用命令.md

  - 其他:
    - Frp 内网穿透搭建: other/Frp 内网穿透搭建.md
    - jookdb重置试用期: other/jookdb重置试用期.md
    - Neo4j 实现一个简单的CMDB管理平台: other/Neo4j 实现一个简单的CMDB管理平台.md
    - SSH隧道代理: other/SSH隧道代理.md
    - task任务构建工具: other/task任务构建工具.md
    - UPX使用方法: other/UPX使用方法.md
    - Wiki.js 安装: other/Wiki.js 安装.md
    - win10右键添加复制文件绝对路径: other/win10右键添加复制文件绝对路径.md
    - 基于订阅号开发属于自己的微信消息通知: other/基于订阅号开发属于自己的微信消息通知.md
    - 软件推荐: other/软件推荐.md
  - Python:
    - 高阶:
      - Python学习笔记-grpc: Python/advanced/Python学习笔记-grpc.md
      - Python学习笔记-property和setter: Python/advanced/Python学习笔记-property和setter.md
      - Python学习笔记-Schema数据结构及类型校验: Python/advanced/Python学习笔记-Schema数据结构及类型校验.md
      - Python学习笔记-with上下文管理器: Python/advanced/Python学习笔记-with上下文管理器.md
      - Python学习笔记-yield用法及优点: Python/advanced/Python学习笔记-yield用法及优点.md
      - Python学习笔记-Zipapp打包可执行文件: Python/advanced/Python学习笔记-Zipapp打包可执行文件.md
      - Python学习笔记-__missing__用法: Python/advanced/Python学习笔记-__missing__用法.md
      - python学习笔记-偏函数: Python/advanced/python学习笔记-偏函数.md
      - Python学习笔记-创建虚拟环境及配置: Python/advanced/Python学习笔记-创建虚拟环境及配置.md
      - Python学习笔记-参数类型提示: Python/advanced/Python学习笔记-参数类型提示.md
      - Python学习笔记-实现链式函数调用: Python/advanced/Python学习笔记-实现链式函数调用.md
      - Python学习笔记-装饰器: Python/advanced/Python学习笔记-装饰器.md
      - Python学习笔记-读取指定文件指定行: Python/advanced/Python学习笔记-读取指定文件指定行.md
      - Python学习笔记-调用dll: Python/advanced/Python学习笔记-调用dll.md
      - Python学习笔记-struct处理二进制数据: Python/advanced/Python学习笔记-struct处理二进制数据.md
      - Python学习笔记-gc垃圾回收: Python/advanced/Python学习笔记-gc垃圾回收.md
    - 其他:
      - Apscheduler 使用Redis集群做为任务存储: Python/other/Apscheduler 使用Redis集群做为任务存储.md
      - 利用Cython对python代码进行加密: Python/other/利用Cython对python代码进行加密.md
      - 解决Pandas安装缺少_bz2模块: Python/other/解决Pandas安装缺少_bz2模块.md
    - 爬虫:
      - JsRpc练习: Python/Spider/JsRpc练习.md
      - Python selenium过图片滑块验证: Python/Spider/Python selenium过图片滑块验证.md
      - Python爬虫-无限VM debugger解决方案: Python/Spider/Python爬虫-无限VM debugger解决方案.md
      - 有道翻译爬虫: Python/Spider/有道翻译爬虫.md
      - 某验五子棋验证码: Python/Spider/某验五子棋验证码.md
    - 基础:
      - 函数: Python/tutorial/函数.md
      - 判断: Python/tutorial/判断.md
      - 安装环境: Python/tutorial/安装环境.md
      - 异常处理: Python/tutorial/异常处理.md
      - 循环: Python/tutorial/循环.md
      - 数据类型: Python/tutorial/数据类型.md
      - 模块: Python/tutorial/模块.md
      - 类: Python/tutorial/类.md