site_name: Wiki
site_url: http://127.0.0.1:8000/
repo_url: https://github.com/jruing/wiki
repo_name: jruing/wiki

use_directory_urls: false
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - toml
    - css
    - javascript
    - typescript
    - python
    - go
    - html
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.expand
    - navigation.top # 返回到顶部
    - content.code.copy #代码复制
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮


nav:
  - 简介:
    - 关于: index.md
  - Python:
    - 基础:
      - 创建虚拟环境及配置: Python/Python 创建虚拟环境及配置.md
      - 读取指定文件指定行: Python/Python 读取指定文件指定行.md

    - 进阶:
      - Schema数据结构: Python/Python学习笔记-Schema数据结构及类型校验.md
      - Python 调用dll: Python/Python 调用dll.md
      - 链式函数调用: Python/Python 实现链式函数调用.md
      - 类型提示: Python/Python代码参数类型提示(Type Hints)笔记.md
      - with上下文管理器: Python/Python上下文管理器with  学习笔记.md
      - yield用法及优点: Python/Python学习笔记-yield用法及优点.md
      - python代码进行加密: Python/利用Cython对python代码进行加密.md
      - context上下文管理器: Python/Golang 学习笔记-context上下文管理器.md
      - property和setter: Python/Python学习笔记-property和setter.md
      - 装饰器: Python/Python学习笔记-装饰器.md
      - 偏函数: Python/python学习笔记-偏函数.md
      - grpc: Python/Python学习笔记-grpc.md
      - 魔术方法-__missing__: Python/Python学习笔记-__missing__用法.md
    - 异常解决访问:
      - 解决Pandas安装缺少_bz2模块: Python/解决Pandas安装缺少_bz2模块.md
    - 其他:
      - Apscheduler使用Redis集群做为任务存储: Python/other/Apscheduler 使用Redis集群做为任务存储.md
      - Zipapp打包可执行文件: Python/other/Python学习笔记-Zipapp打包可执行文件.md
    - 爬虫:
      - JsRPC练习: Python/Spider/JsRpc练习.md
      - 有道翻译爬虫: Python/Spider/有道翻译爬虫.md
      - selenium过图片滑块验证: Python/Spider/Python selenium过图片滑块验证.md
      - 某验五子棋验证码: Python/Spider/某验五子棋验证码.md
      - 无限VM debugger解决方案: Python/Spider/Python爬虫-无限VM debugger解决方案.md
  - Golang:
    - 基础:
      - 常量: Golang/Golang学习笔记-常量.md
      - 变量: Golang/Golang学习笔记-变量.md
      - 判断: Golang/Golang学习笔记-判断.md
      - 循环: Golang/Golang学习笔记-循环.md
      - 数据类型: Golang/Golang学习笔记-数据类型.md
      - 结构体与匿名结构体: Golang/Golang 学习笔记-结构体与匿名结构体.md
    - 进阶:
      - Viper配置解析: Golang/Golang 学习笔记-Viper.md
      - JWT使用: Golang/Golang学习笔记-jwt.md
      - Casbin权限管理: Golang/Golang学习笔记-Casbin学习笔记.md
    - 其他: 
      - 定时任务: Golang/Golang学习笔记-定时任务.md
      - 跨平台编译: Golang/Golang 跨平台编译.md
      - 自定义日志轮转及输出: Golang/Golang学习笔记-自定义日志轮转及输出.md
      - 处理HTTP请求参数: Golang/Golang学习笔记-处理HTTP请求参数.md
      - Corba CLI: Golang/Corba CLI 学习笔记.md
      - sqlc代码生成: Golang/Golang 学习笔记-sqlc 代码生成.md

  - 数据库:
    - Postgres:
      - 安装: database/postgres/postgres安装.md
      - Sequence自增序列: database/postgres/Postgres学习笔记-Sequence自增序列.md
    - Redis:
      - Redis集群: database/postgres/Redis7.XCentos集群搭建.md
    - MySQL:
      - Mysql5.7绿色版安装: database/mysql/Mysql5.7 绿色版安装.md
  - 自动化:
    - Selenium: automation/Selenium接管已打开的浏览器.md
  - 容器化:
    - Docker:
      - Docker在线安装教程: kubernetes/Docker 在线安装教程.md
      - Docker-compose安装: kubernetes/Docker-Compose安装.md
      - DockerSwarm: kubernetes/Docker Swarm 学习笔记.md
      - Docker镜像仓库搭建: kubernetes/Docker-构建私有镜像仓库.md
      - 容器镜像导入导出: kubernetes/Docker笔记-容器镜像导入导出.md
      - Docker常用小技巧: kubernetes/Docker 常用技巧.md
      - 安装Nginx及实践应用: kubernetes/Docker 安装Nginx及实践应用.md
      - 多阶段构建学习笔记: kubernetes/Docker 多阶段构建学习笔记.md
      - 镜像体积缩小: kubernetes/Docker 镜像体积缩小.md
    - kubernetes:
      - 安装: kubernetes/kubernetes学习笔记-安装.md
      - Pod: kubernetes/kubernetes学习笔记-Pod.md
      - NameSpace: kubernetes/kubernetes学习笔记-namespace.md
      - ReplicaSet: kubernetes/kubernetes学习笔记-ReplicaSet.md
      - Depolyment: kubernetes/kubernetes学习笔记-Depolyment.md
      - Service: kubernetes/kubernetes学习笔记-Service.md
      - ConfigMap: kubernetes/kubernetes学习笔记-ConfigMap.md
      - Ingress: kubernetes/kubernetes学习笔记-Ingress.md
      - helm学习笔记: kubernetes/helm学习笔记.md
  - Linux:
    - Nginx:
      - 简介: Linux/nginx/Nginx学习笔记-Nginx简介.md
      - 安装Nginx: Linux/nginx/Nginx学习笔记-Centos 7 安装Nginx.md
      - 配置文件详解: Linux/nginx/Nginx学习笔记-配置文件详解.md
      - 部署静态页面实践: Linux/nginx/Nginx学习笔记-部署静态页面实践.md
      - auth_basic认证: Linux/nginx/Nginx学习笔记-auth_basic认证.md
      - 负载均衡配置: Linux/nginx/Nginx学习笔记-负载均衡配置.md
      - 图片防盗链: Linux/nginx/Nginx学习笔记-图片防盗链.md
      - 黑/白名单: Linux/nginx/Nginx学习笔记-黑名单-白名单.md
      - 前端后端跨域: Linux/nginx/Nginx学习笔记-解决前端后端跨域.md
    - caddy:
      - 简介: Linux/caddy/caddy简介.md
      - 安装: Linux/caddy/caddy安装.md
      - 静态文件目录: Linux/caddy/caddy静态文件.md
      - 静态站点: Linux/caddy/caddy实战-静态站点.md
      - BasicAuth: Linux/caddy/caddy实战-basicauth.md
    - 监控:
      - Loki日志监控: Linux/monitor/基于Grafana+Loki+Promatil搭建日志分析平台.md
      - Uptime-kuma监控: Linux/monitor/Uptime-kuma 监控.md
    - Prometheus:
      - 安装: Linux/Prometheus/Prometheus笔记-安装.md
      - 配置文件字段解析: Linux/Prometheus/Prometheus笔记-配置文件字段解析.md
      - 基于文件发现: Linux/Prometheus/Prometheus笔记-file_sd_config.md
      - 安装Node_exporter: Linux/Prometheus/Prometheus笔记-安装Node_exporter.md
      - 安装blackbox_exporter: Linux/Prometheus/Prometheus笔记-安装blackbox_exporter.md
      - 监控docker容器: Linux/Prometheus/Prometheus笔记-监控docker容器.md
      - 设置Basic_auth登录校验: Linux/Prometheus/Prometheus笔记-设置Basic_auth登录校验.md
      - Label标签: Linux/Prometheus/Prometheus笔记-Label标签.md
      - 告警规则配置: Linux/Prometheus/Prometheus笔记-告警规则配置.md
      - Grafana可视化: Linux/Prometheus/Prometheus笔记-Grafana可视化.md
    - 其他:
      - Systemd: Linux/other/Systemd 学习笔记.md
      - FTP服务: Linux/other/Centos7 搭建FTP服务.md
      - Linux免密登录: Linux/other/Linux免密登录.md

  - ServerLess:
    - Fnproject: 
      - 搭建: Linux/serverless/ServerLess学习笔记-Fnproject搭建.md
      - 常用命令: Linux/serverless/ServerLess学习笔记-Fnproject常用命令.md
      - 示例: Linux/serverless/ServerLess学习笔记-搭建FN示例.md
  - 前端:
    - Javascript: 
      - js拷贝复制: front/Javascript学习笔记-js实现拷贝复制功能.md
    - React:
      - 基础:
        - 安装: front/React/React-安装.md
        - JSX语法: front/React/React-JSX.md
        - 数据展示: front/React/React-数据展示.md
        - 条件判断: front/React/React-条件判断.md
        - 列表渲染: front/React/React-列表渲染.md
        - 响应事件: front/React/React-响应事件.md
        - 更新页面数据: front/React/React-更新页面数据.md
        - Props传递给组件: front/React/React-Props传递给组件.md
    - Vue3:
      - 进阶:
        - 基础环境搭建: front/Vue/Vue3+Vite项目基础环境搭建.md
        - Router路由管理: front/Vue/Vue3 Router路由.md
  - AI:
    - 提示词:
      - 嘴替: AI/prompt/嘴替.md
    - AI应用:
      - AnythingLLM搭建RAG: AI/AnythingLLM+Ollama搭建本地知识库.md
      - OneAPI搭建: AI/Docker安装OneAPI.md
      - MCP学习笔记: AI/MCP学习笔记.md
      - LlamaIndex-Agent查询数据库: AI/LlamaIndex-Agent关联数据库.md
      - LlamaIndex-Agent自然语言查询数据库: AI/Llamaindex-Agent自然语言查询数据库.md
  - 未分类:
    - UPX: other/UPX使用方法.md
    - 订阅号消息通知: other/基于订阅号开发属于自己的微信消息通知.md
    - Neo4j实现一个简单的CMDB管理平台: other/Neo4j 实现一个简单的CMDB管理平台.md
    - Wiki.js安装: other/Wiki.js 安装.md
    - Frp内网穿透搭建: other/Frp 内网穿透搭建.md
    - jookdb重置试用期: other/jookdb重置试用期.md
    - task任务构建工具: other/task任务构建工具.md
